= User access provision
:toc:
:toclevels: 2
:sectnums:

== Purpose
This standard operating procedure (SOP) standardizes access provision for all eligible associates and contains the steps necessary to provide, revoke or reassign access to ABC's internal applications.

== Scope
This document is applicable for IT admins and support engineers. This does not cover access provison for external websites or applications.

== Definitions
The following table describes the terms used in the document.
|===
| *Term* | *Description*

| IAM
| Identity and Access Management refers to the process of managing user identities and system-access controls.

|Requestor
|This refers to the associate who has requested access to any system or application.

|Approver
|This refers to the designated approver (associate) who approves and grants access to the requested application.
|===

== Roles and responsibilities
The following table lists the roles and responsibilities of the associates involved in access provisioning.
|===
| *Role* | *Responsibility* | *Restrictions*

|Requestor
|*Requests* access to necessary applications and *provides* justification for access.
|*Cannot* approve any requests.

|Approver
|*Approves* the access requests and grants access. _For example_, a manager or an admin.
|*Cannot* approve requests without any valid business justification.

|IT administrator
|*Authorizes*, *reviews*, *documents*, and *manages* the user access provision processes.
|*Cannot* grant access without approvals or deviate from the SOP.
|===

== Prerequisites
* *Employee status* - *Ensure* to check if the requestor has an active and valid presence in the organization.
* *Formal access request* - *Ensure* to *only* accept requests that are submitted using the internal portal. Do not approve requests that are shared through any other channels.
* *Completion of security training* - *Ensure* that the requestor has completed the security training before granting access.

== Procedure
*Phase 1. Access Request Initiation*

The following steps are performed by the requestor.

. *Submit* an access request through the internal portal.
. *Add* the business justification and manager's name for the access request.
